"""
Django settings for Portfolio project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (fails safe) — local dev must opt in explicitly rather than
# a forgotten env var silently leaving a production deploy in debug mode.
# Run locally with DJANGO_DEBUG=True (see README) to get tracebacks + the dev key below.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# The insecure fallback only applies in DEBUG; production (DEBUG=False) must set
# DJANGO_SECRET_KEY or fail to start rather than silently serving on a key that's
# been public in this repo's git history since day one.
if DEBUG:
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-local-dev-only-key')
else:
    SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()
]

# HTTPS/proxy/cookie hardening — gated on DEBUG so a bare local `runserver` (no TLS)
# isn't broken by an SSL redirect or Secure-flagged cookies it can never satisfy.
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '31536000'))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Set when running behind a TLS-terminating proxy/load balancer (the common case for
    # most hosts) so Django trusts X-Forwarded-Proto instead of seeing every request as
    # plain HTTP and redirect-looping. Set DJANGO_BEHIND_PROXY=False if TLS terminates
    # in the app process itself.
    if os.environ.get('DJANGO_BEHIND_PROXY', 'True') == 'True':
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Needed once this is served from a real domain behind HTTPS — Django's CSRF check
# compares the Origin header against this list for unsafe (POST/PUT/etc.) requests.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'DesignWithCory',
    'crm',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Immediately after SecurityMiddleware per WhiteNoise's own placement guidance, so
    # static files are served as early in the chain as possible.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Default is DENY, which — discovered by actually testing behind WhiteNoise/production
# static serving rather than DEBUG's dev-server static handler, which bypasses this
# middleware entirely — silently broke the Work Samples page's same-origin Pattern Atlas
# iframe embed (static/lab/pattern-atlas.html framed by the page that ships it). This
# site never frames anything cross-origin, so SAMEORIGIN is the correct, still-safe value.
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'Portfolio.urls'
STATIC_ROOT = BASE_DIR / 'productionfiles'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'DesignWithCory.context_processors.site_contact',
            ],
        },
    },
]

WSGI_APPLICATION = 'Portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASE_URL (postgres://user:pass@host:port/dbname) drives this in Docker/production —
# see docker-compose.yml. Left unset (or blank, as it ships in .env.example), local
# development still works unchanged against a plain SQLite file. dj_database_url.config()
# only applies its default when the env var is absent, not when it's present-but-empty,
# so an empty string is normalized away here before it reaches that call.
DATABASES = {
    'default': dj_database_url.parse(
        os.environ.get('DATABASE_URL') or f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# User/admin-uploaded files: CRM notes/attachments, work-sample images, the resume PDF.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django serves MEDIA_ROOT itself by default (see urls.py) — not just in DEBUG. That's
# the right tradeoff at this project's actual traffic level: simple, and it means the
# Docker deployment doesn't need a second web server just for uploaded images. Set to
# False and front /media/ with something else (nginx, a cloud storage backend via
# django-storages, a CDN) if traffic ever justifies it.
SERVE_MEDIA_VIA_DJANGO = os.environ.get('DJANGO_SERVE_MEDIA', 'True') == 'True'
# Every upload in this project goes through the admin (there's no public upload
# endpoint), but a generous outer ceiling still guards against a request tying up a
# worker or filling disk. Deliberately set above the largest per-field limit in
# DesignWithCory/validators.py (15MB) so it's a safety net, not the real limit —
# the model validators are what actually enforce sane, field-specific sizes.
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/4.2/topics/email/
# Defaults to printing mail to the console so the contact form works out of
# the box in dev; set DJANGO_EMAIL_HOST (+ USER/PASSWORD) to send for real.
if os.environ.get('DJANGO_EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ['DJANGO_EMAIL_HOST']
    EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.environ.get('DJANGO_EMAIL_USE_TLS', 'True') == 'True'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Single source of truth for the phone number shown site-wide (DesignWithCory.
# context_processors.site_contact) — was hardcoded independently in both footer.html and
# lead_gen.html. TEL is the tel:-href-safe form (digits + leading +, no formatting).
SITE_PHONE_DISPLAY = os.environ.get('DJANGO_SITE_PHONE_DISPLAY', '+1 (610) 413-6101')
SITE_PHONE_TEL = os.environ.get('DJANGO_SITE_PHONE_TEL', '+16104136101')

DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'Inquiry@DesignWithCory.com')
# Where contact-form leads get emailed — defaults to DEFAULT_FROM_EMAIL rather than
# repeating the address as a second hardcoded literal.
CONTACT_NOTIFICATION_EMAIL = os.environ.get(
    'DJANGO_CONTACT_NOTIFICATION_EMAIL', DEFAULT_FROM_EMAIL
)

# If set, Django emails a full traceback here on any unhandled 500 (only takes effect
# with DEBUG=False, and only actually sends if EMAIL_BACKEND above is real SMTP).
_admin_email = os.environ.get('DJANGO_ADMIN_EMAIL')
ADMINS = [('Cory Comly', _admin_email)] if _admin_email else []
SERVER_EMAIL = os.environ.get('DJANGO_SERVER_EMAIL', DEFAULT_FROM_EMAIL)
