# Generated by Django 4.2.30 on 2026-08-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='project_summary',
            field=models.TextField(blank=True, default='', help_text='What they want built, in their own words.'),
        ),
    ]
