# Generated by Django 4.2.30 on 2026-08-22 03:29

import DesignWithCory.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_lead_project_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='crm_attachments/%Y/%m/', validators=[DesignWithCory.validators.validate_document_upload_size]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_type', 'object_id'], name='crm_attachm_content_c4dd43_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['content_type', 'object_id'], name='crm_note_content_76ab87_idx'),
        ),
    ]
