# Generated by Django 4.2.30 on 2026-08-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(help_text="Short one-line role/type, e.g. 'Mobile app'.", max_length=200)),
                ('description', models.TextField()),
                ('display_type', models.CharField(choices=[('image', 'Image'), ('iframe', 'Embedded iframe'), ('grandiose', 'Grandiose (full-width, multi-view)')], default='image', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='work_samples/')),
                ('embed_url', models.CharField(blank=True, help_text='Relative or absolute URL for display_type=iframe.', max_length=300)),
                ('repo_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
