# Generated by Django 4.2.30 on 2026-08-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignWithCory', '0002_seed_work_samples'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('cover_image', models.FileField(help_text='Shown on the blog card and post header.', upload_to='blog/')),
                ('excerpt', models.TextField(help_text='First-paragraph teaser shown on the card, above the fade-out.')),
                ('body', models.TextField(help_text='Full post. Paragraphs (blank-line separated) are rendered as <p>.')),
                ('published_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
