# Generated by Django 4.2.30 on 2026-08-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignWithCory', '0004_seed_blog_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resume/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
