# Generated by Django 4.2.30 on 2026-08-22 03:29

import DesignWithCory.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignWithCory', '0007_estimate_backend_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.FileField(help_text='Shown on the blog card and post header.', upload_to='blog/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg']), DesignWithCory.validators.validate_image_upload_size]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resume/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), DesignWithCory.validators.validate_document_upload_size]),
        ),
        migrations.AlterField(
            model_name='worksample',
            name='embed_url',
            field=models.CharField(blank=True, help_text='Relative or absolute URL for display_type=iframe.', max_length=300, validators=[DesignWithCory.validators.validate_embed_url]),
        ),
        migrations.AlterField(
            model_name='worksample',
            name='image',
            field=models.ImageField(blank=True, upload_to='work_samples/', validators=[DesignWithCory.validators.validate_image_upload_size]),
        ),
    ]
